export const REQUEST_INVOKE_FUNCTION = 'REQUEST_INVOKE_FUNCTION';
export const REQUEST_INVOKE_FAILED = 'REQUEST_INVOKE_FAILED';
export const SUCCESSS_INVOKE_FUNCTION = 'SUCCESSS_INVOKE_FUNCTION';
export const SET_CONSOLE_STATE_NEUTRAL = 'SET_CONSOLE_STATE_NEUTRAL';
export const RESET_OUTPUT = 'RESET_OUTPUT';

export const CONSOLE_STATE = {
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  NEUTRAL: 'NEUTRAL'
};
