export const REQUEST_INVOKE_FUNCTION = 'REQUEST_INVOKE_FUNCTION';
export const REQUEST_INVOKE_FAILED = 'REQUEST_INVOKE_FAILED';
export const ADD_OUTPUT = 'ADD_OUTPUT';
export const SET_CONSOLE_STATE_NEUTRAL = 'SET_CONSOLE_STATE_NEUTRAL';
export const RESET_OUTPUT = 'RESET_OUTPUT';

export const CONSOLE_STATE = {
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  NEUTRAL: 'NEUTRAL'
};

export const MESSAGE_TYPE = {
  INVOKE_SUCCESS_OUTPUT: 'INVOKE_SUCCESS_OUTPUT',
  INVOKE_FAILURE_OUTPUT: 'INVOKE_FAILURE_OUTPUT'
};
