export const PARAMETER_PANEL_INIT = 'PARAMETER_PANEL_INIT';
export const TOGGLE_CODE_TREE = 'TOGGLE_CODE_TREE';

export const NAMESPACE_STATES = {
  INVALID: 'INVALID',
  PENDING: 'PENDING',
  CREATED: 'CREATED'
};

export const NODE_TYPES = {
  NAMESPACE: 'NAMESPACE',
  FUNCTION: 'FUNCTION',
  NEW_FUNCTION: 'NEW_FUNCTION',
  EMPTY: 'EMPTY',
};

export const SET_NAME_SPACE_STATE = 'SET_NAME_SPACE_STATE';
export const SET_NEW_NAME_SPACE_VALUE = 'SET_NEW_NAME_SPACE_VALUE';
export const CREATE_NEW_NAME_SPACE_REQEUST = 'CREATE_NEW_NAME_SPACE_REQEUST';
export const CREATE_NEW_NAME_SPACE_PENDING = 'CREATE_NEW_NAME_SPACE_PENDING';

// EMITTED BY SAGAS
export const SAGA_SET_PARAMETER_PANEL_CHILDREN = 'SAGA_SET_PARAMETER_PANEL_CHILDREN';
