export const PARAMETER_PANEL_INIT = 'PARAMETER_PANEL_INIT';
export const TOGGLE_CODE_TREE = 'TOGGLE_CODE_TREE';
export const TOGGLE_DB_TREE = 'TOGGLE_DB_TREE';

export const NAMESPACE_STATES = {
  INVALID: 'INVALID',
  PENDING: 'PENDING',
  CREATED: 'CREATED'
};

export const NODE_TYPES = {
  NAMESPACE: 'NAMESPACE',
  FUNCTION: 'FUNCTION',
  NEW_FUNCTION: 'NEW_FUNCTION',
  EMPTY: 'EMPTY',
};

export const TABLE_NODE_TYPES = {
  TABLE: 'TABLE',
  COLUMN: 'COLUMN'
};

export const PARAMETER_TYPES = {
  NS_FUNC: 'NS_FUNC',
  LOADING: 'LOADING',
  DATABASES: 'DATABASES'
};

export const SET_NAME_SPACE_STATE = 'SET_NAME_SPACE_STATE';
export const SET_NEW_NAME_SPACE_VALUE = 'SET_NEW_NAME_SPACE_VALUE';
export const CREATE_NEW_NAME_SPACE_REQEUST = 'CREATE_NEW_NAME_SPACE_REQEUST';
export const CREATE_NEW_NAME_SPACE_PENDING = 'CREATE_NEW_NAME_SPACE_PENDING';

export const REQUEST_SHOW_DB_PARAMETER = 'REQUEST_SHOW_DB_PARAMETER';
export const SET_SELECTED_PARAMETER_NS_FUNC = 'SET_SELECTED_PARAMETER_NS_FUNC';
export const SET_SELECTED_PARAMETER_DB = 'SET_SELECTED_PARAMETER_DB';
export const SET_SELECTED_PARAMETER_LOADING = 'SET_SELECTED_PARAMETER_LOADING';

// EMITTED BY SAGAS
export const SAGA_SET_NS_CHILDREN = 'SAGA_SET_NS_CHILDREN';
export const SAGA_SET_DB_CHILDREN = 'SAGA_SET_DB_CHILDREN';
