export const PARAMETER_PANEL_INIT = 'PARAMETER_PANEL_INIT';
export const TOGGLE_CODE_TREE = 'TOGGLE_CODE_TREE';

// EMITTED BY SAGAS
export const SAGA_SET_PARAMETER_PANEL_CHILDREN = 'SAGA_SET_PARAMETER_PANEL_CHILDREN';
