export const SHOW_FUNCTION_REQUEST = 'SHOW_FUNCTION_REQUEST';
export const SAGA_SHOW_FUNCTION_SET_CODE_PANEL = 'SAGA_SHOW_FUNCTION_SET_CODE_PANEL';

export const SET_STORE_CODE = 'SET_STORE_CODE';

export const REQUEST_UPDATE_CODE = 'REQUEST_UPDATE_CODE';
