export const SHOW_FUNCTION_REQUEST = 'SHOW_FUNCTION_REQUEST';
export const SAGA_SHOW_FUNCTION_SET_CODE_PANEL = 'SAGA_SHOW_FUNCTION_SET_CODE_PANEL';

export const SET_STORE_CODE = 'SET_STORE_CODE';
export const SET_TEST_CODE = 'SET_TEST_CODE';

export const SET_TEST_CODE_ERROR = 'SET_TEST_CODE_ERROR';

export const SET_PANEL_EMPTY = 'SET_PANEL_EMPTY';

export const REQUEST_UPDATE_CODE = 'REQUEST_UPDATE_CODE';

export const SHOW_NEW_FUNCTION = 'SHOW_NEW_FUNCTION';

export const REQUEST_CREATE_FUNCTION = 'REQUEST_CREATE_FUNCTION';
export const REQUEST_DELETE_FUNCTION = 'REQUEST_DELETE_FUNCTION';
export const REQUEST_DELETE_NAMESPACE = 'REQUEST_DELETE_NAMESPACE';
